singUp testing
wolox-training/df-express-js pull request #5
Opened 2018-10-08 15:52 UTC by dantefarias

## Summary

* Test from Sing up

## Trello Card
* Tests and documentation from Sing Up:

https://trello.com/c/7D9TGPlX/28-tests-y-documentaci%C3%B3n-de-sign-up

2018-10-08 16:51 UTC, mpizzagalli requested changes
It's very importante to think all the things we want or need to test given a feature. Otherwise somebody can change the code like a refactor, fix or some addition to the feature an easily break the feature and if the tests doesn't cover all the thing we want, maybe they wont fail.

2018-10-08 16:51 UTC, mpizzagalli commented on app/middlewares/errors.js
> +  if (error && error.statusCode) {
why did you changed this?

2018-10-08 16:51 UTC, mpizzagalli commented on test/user.js
> +          err.should.have.status(400);
with this you are testing that the server response is an error, but we aren't checking that we are not creating a new user. Maybe the server is responding the error but its also creating an invalid user.

2018-10-08 16:51 UTC, mpizzagalli commented on test/user.js
> +          res.should.have.status(200);
Also here we should check that we are actually creating a new user.

2018-10-08 18:02 UTC, dantefarias commented on app/middlewares/errors.js
> +  if (error && error.statusCode) {
Because, I was getting an UnhandledPromiseRejectionWarning: AssertionError: expected [Error: Internal Server Error] to have status code 400 but got 500.
So I think that may be, it was the problem.

2018-10-09 14:06 UTC, mpizzagalli approved these changes

2018-10-09 14:49 UTC, merged